// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwedesEventPlanner.Infrastructure.Persistence;

#nullable disable

namespace SwedesEventPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventPlannerDbContext))]
    [Migration("20260622123956_ProgressScopeUniqueIndexes")]
    partial class ProgressScopeUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountProfileType")
                        .HasColumnType("text")
                        .HasColumnName("account_profile_type");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_type");

                    b.Property<string>("BossName")
                        .HasColumnType("text")
                        .HasColumnName("boss_name");

                    b.Property<string>("DedupeKey")
                        .HasColumnType("text")
                        .HasColumnName("dedupe_key");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int?>("Kc")
                        .HasColumnType("integer")
                        .HasColumnName("kc");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Skill")
                        .HasColumnType("text")
                        .HasColumnName("skill");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceEndpoint")
                        .HasColumnType("text")
                        .HasColumnName("source_endpoint");

                    b.Property<string>("SourcePayloadVersion")
                        .HasColumnType("text")
                        .HasColumnName("source_payload_version");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<long?>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("idx_activity_events_dedupe_key")
                        .HasFilter("dedupe_key IS NOT NULL");

                    b.HasIndex("ActivityType", "OccurredAt")
                        .HasDatabaseName("idx_activity_events_type_time");

                    b.HasIndex("PlayerId", "OccurredAt")
                        .HasDatabaseName("idx_activity_events_player_time");

                    b.ToTable("activity_events", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityEventItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_event_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ActivityEventId")
                        .HasDatabaseName("idx_activity_event_items_activity");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("idx_activity_event_items_item");

                    b.ToTable("activity_event_items", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityEventMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_event_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool?>("MetricBool")
                        .HasColumnType("boolean")
                        .HasColumnName("metric_bool");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_type");

                    b.Property<long?>("MetricValue")
                        .HasColumnType("bigint")
                        .HasColumnName("metric_value");

                    b.HasKey("Id");

                    b.HasIndex("ActivityEventId");

                    b.ToTable("activity_event_metrics", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityProcessingQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_event_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ActivityEventId");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("idx_activity_processing_queue_pending");

                    b.ToTable("activity_processing_queue", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.BingoBoard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<int?>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("bingo_boards", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.BingoTile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("board_id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("PositionX")
                        .HasColumnType("integer")
                        .HasColumnName("position_x");

                    b.Property<int?>("PositionY")
                        .HasColumnType("integer")
                        .HasColumnName("position_y");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("bingo_tiles", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.BingoTileTier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequiredForBoardCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required_for_board_completion");

                    b.Property<int>("ScoreValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("score_value");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("TierNumber")
                        .HasColumnType("integer")
                        .HasColumnName("tier_number");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("TileId", "TierNumber")
                        .IsUnique();

                    b.ToTable("bingo_tile_tiers", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.EventProgressContribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActivityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_id");

                    b.Property<long?>("TileTierId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_tier_id");

                    b.Property<decimal>("ValueAdded")
                        .HasColumnType("numeric")
                        .HasColumnName("value_added");

                    b.HasKey("Id");

                    b.HasIndex("ActivityEventId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RuleId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TileId");

                    b.HasIndex("TileTierId");

                    b.HasIndex("EventId", "TileId", "RuleId", "ActivityEventId")
                        .IsUnique()
                        .HasFilter("activity_event_id IS NOT NULL");

                    b.ToTable("event_progress_contributions", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.EventTileProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_tier");

                    b.Property<decimal>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_value");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TileId");

                    b.HasIndex("EventId", "TileId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_tile_progress_event_scope")
                        .HasFilter("team_id IS NULL AND player_id IS NULL");

                    b.HasIndex("EventId", "TileId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_tile_progress_player_scope")
                        .HasFilter("team_id IS NULL AND player_id IS NOT NULL");

                    b.HasIndex("EventId", "TileId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_tile_progress_team_scope")
                        .HasFilter("team_id IS NOT NULL AND player_id IS NULL");

                    b.ToTable("event_tile_progress", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.EventTileTierProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<decimal>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_value");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsAchieved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_achieved");

                    b.Property<bool>("IsScored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_scored");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("ScoreAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score_awarded");

                    b.Property<DateTimeOffset?>("ScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_id");

                    b.Property<long>("TileTierId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_tier_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TileId");

                    b.HasIndex("TileTierId");

                    b.HasIndex("EventId", "TileTierId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_tile_tier_progress_event_scope")
                        .HasFilter("team_id IS NULL AND player_id IS NULL");

                    b.HasIndex("EventId", "TileTierId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_tile_tier_progress_player_scope")
                        .HasFilter("team_id IS NULL AND player_id IS NOT NULL");

                    b.HasIndex("EventId", "TileTierId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_tile_tier_progress_team_scope")
                        .HasFilter("team_id IS NOT NULL AND player_id IS NULL");

                    b.ToTable("event_tile_tier_progress", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.TileRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_type");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_id");

                    b.Property<long?>("TileTierId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_tier_id");

                    b.HasKey("Id");

                    b.HasIndex("TileId");

                    b.HasIndex("TileTierId");

                    b.ToTable("tile_rules", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.TileUnlockCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_type");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tile_id");

                    b.HasKey("Id");

                    b.HasIndex("TileId");

                    b.ToTable("tile_unlock_conditions", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Europe/Stockholm")
                        .HasColumnName("time_zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status", "StartsAt", "EndsAt")
                        .HasDatabaseName("idx_events_active_window");

                    b.ToTable("events", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("EventId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("PlayerId", "EventId", "Status")
                        .HasDatabaseName("idx_event_participants_player");

                    b.ToTable("event_participants", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventSignup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("AvailabilityText")
                        .HasColumnType("text")
                        .HasColumnName("availability_text");

                    b.Property<decimal?>("DailyHours")
                        .HasColumnType("numeric")
                        .HasColumnName("daily_hours");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailHash")
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PreferredContent")
                        .HasColumnType("text")
                        .HasColumnName("preferred_content");

                    b.Property<string>("RuneScapeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("runescape_name");

                    b.Property<string>("SourceRowHash")
                        .HasColumnType("text")
                        .HasColumnName("source_row_hash");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("google_forms")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("imported")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TeamPreference")
                        .HasColumnType("text")
                        .HasColumnName("team_preference");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("EventId", "SourceSystem", "SourceRowHash")
                        .IsUnique();

                    b.ToTable("event_signups", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Name")
                        .IsUnique();

                    b.ToTable("event_teams", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("CompetitionMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unknown")
                        .HasColumnName("competition_mode");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastPublicSyncRequestAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_public_sync_request_accepted_at");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_sync_at");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_status");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextPublicSyncAvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_public_sync_available_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("SecretReference")
                        .HasColumnType("text")
                        .HasColumnName("secret_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("external_competitions", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionExportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long>("ExternalCompetitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_competition_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int?>("ParticipantsAdded")
                        .HasColumnType("integer")
                        .HasColumnName("participants_added");

                    b.Property<int?>("ParticipantsIntended")
                        .HasColumnType("integer")
                        .HasColumnName("participants_intended");

                    b.Property<int?>("ParticipantsRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("participants_removed");

                    b.Property<string>("RequestSummaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_summary_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ResponseSummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_summary_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TeamMappingsIntended")
                        .HasColumnType("integer")
                        .HasColumnName("team_mappings_intended");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.Property<string>("ValidationSummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_summary_json");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ExternalCompetitionId");

                    b.ToTable("external_competition_export_runs", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.Property<long>("ExternalCompetitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_competition_id");

                    b.Property<long?>("ExternalCompetitionPlayerReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_competition_player_review_id");

                    b.Property<long?>("ExternalPlayerIdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_player_identity_id");

                    b.Property<long>("GainedValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("gained_value");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_type");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("RuneScapeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("runescape_name");

                    b.Property<long?>("StartValue")
                        .HasColumnType("bigint")
                        .HasColumnName("start_value");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCompetitionPlayerReviewId");

                    b.HasIndex("ExternalPlayerIdentityId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ExternalCompetitionId", "RuneScapeName", "MetricType", "MetricKey")
                        .IsUnique();

                    b.ToTable("external_competition_metrics", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionPlayerReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("ExternalCompetitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_competition_id");

                    b.Property<long>("ExternalPlayerIdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_player_identity_id");

                    b.Property<DateTimeOffset?>("IgnoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ignored_at");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unreviewed")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlayerIdentityId");

                    b.HasIndex("ExternalCompetitionId", "ExternalPlayerIdentityId")
                        .IsUnique();

                    b.ToTable("external_competition_player_reviews", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionSyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("ExternalCompetitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_competition_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response_json");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int?>("RowsChanged")
                        .HasColumnType("integer")
                        .HasColumnName("rows_changed");

                    b.Property<int?>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCompetitionId")
                        .IsUnique()
                        .HasDatabaseName("idx_external_competition_sync_runs_one_active")
                        .HasFilter("status IN ('queued', 'running')");

                    b.ToTable("external_competition_sync_runs", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionTeamMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.Property<long>("ExternalCompetitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_competition_id");

                    b.Property<long>("GainedValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("gained_value");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<long?>("LocalTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("local_team_id");

                    b.Property<string>("MembersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("members_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_key");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_type");

                    b.Property<string>("MvpRuneScapeName")
                        .HasColumnType("text")
                        .HasColumnName("mvp_runescape_name");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<long?>("StartValue")
                        .HasColumnType("bigint")
                        .HasColumnName("start_value");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_name");

                    b.Property<string>("TempleTeamKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("temple_team_key");

                    b.HasKey("Id");

                    b.HasIndex("LocalTeamId");

                    b.HasIndex("ExternalCompetitionId", "TempleTeamKey", "MetricType", "MetricKey")
                        .IsUnique();

                    b.ToTable("external_competition_team_metrics", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Items.ItemGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("item_groups", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Items.ItemGroupItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("ItemGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_group_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId", "ItemId")
                        .IsUnique();

                    b.ToTable("item_group_items", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Players.ExternalPlayerIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_identifier");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unmatched")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Provider", "ExternalIdentifier")
                        .IsUnique();

                    b.ToTable("external_player_identities", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Players.LinkedAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_identifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Provider", "ExternalIdentifier")
                        .IsUnique();

                    b.ToTable("linked_accounts", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Players.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("RuneScapeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("runescape_name");

                    b.HasKey("Id");

                    b.HasIndex("RuneScapeName")
                        .IsUnique();

                    b.ToTable("players", "public");
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityEvent", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityEventItem", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Activity.ActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityEventMetric", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Activity.ActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Activity.ActivityProcessingQueueItem", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Activity.ActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.BingoBoard", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.BingoTile", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoBoard", null)
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.BingoTileTier", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.EventProgressContribution", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Activity.ActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.TileRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Events.EventTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTileTier", null)
                        .WithMany()
                        .HasForeignKey("TileTierId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.EventTileProgress", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwedesEventPlanner.Domain.Events.EventTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.EventTileTierProgress", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwedesEventPlanner.Domain.Events.EventTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTileTier", null)
                        .WithMany()
                        .HasForeignKey("TileTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.TileRule", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTileTier", null)
                        .WithMany()
                        .HasForeignKey("TileTierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Bingo.TileUnlockCondition", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Bingo.BingoTile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventParticipant", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Events.EventTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventSignup", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Events.EventTeam", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionExportRun", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Events.EventDefinition", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionMetric", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionPlayerReview", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompetitionPlayerReviewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwedesEventPlanner.Domain.Players.ExternalPlayerIdentity", null)
                        .WithMany()
                        .HasForeignKey("ExternalPlayerIdentityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionPlayerReview", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Players.ExternalPlayerIdentity", null)
                        .WithMany()
                        .HasForeignKey("ExternalPlayerIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionSyncRun", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetitionTeamMetric", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.ExternalCompetitions.ExternalCompetition", null)
                        .WithMany()
                        .HasForeignKey("ExternalCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwedesEventPlanner.Domain.Events.EventTeam", null)
                        .WithMany()
                        .HasForeignKey("LocalTeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Items.ItemGroupItem", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Items.ItemGroup", null)
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Players.ExternalPlayerIdentity", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwedesEventPlanner.Domain.Players.LinkedAccount", b =>
                {
                    b.HasOne("SwedesEventPlanner.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
